apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xif9onfbq-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c928f487e0.43p6.p3.openshiftapps.com/rhtap/rhtap-qe-java-quarkus:5a639e0727c9f64ba1bf29c88e4e3e955f3f70fd@sha256:a522783b46ea7270552017b473320f6864d130a7e8619593d8e71ca5ad53fe24
          name: container-image
